# 数据源
 spring:
  datasource:
     name: test
     type: com.alibaba.druid.pool.DruidDataSource
     url: jdbc:mysql://192.168.92.129:3306/test?useSSL=true
     username: root
     password: 123456
     dirver-class-name: com.mysql.jdbc.Driver
     
  mvc:
    view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp